name: Niclas Kristiansson
favicon: null
layout_spectrum: 0.10223588044755161
typography_spectrum: 0.15415482921525836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7070692731067538
  lightness: 0.18265971937216818
  saturation: 0.7186662855092436
  rhythmicContrast: 0.09673986514098942
purpose: []
